#
# Setup the services locally
#
version: '3.7'
networks:
  local:
  monitoring:

volumes: 
  prometheus-data:
  grafana-data:

services:
  db:
    image: mysql:5
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  nats:
    image: nats:latest
    networks:
      - local
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222  
  user:
    build: $GOPATH/src/github.com/Bachelor-project-f20/users_poc
    networks:
      - local
    depends_on:
      - db
      - nats
    environment:
      NATS_BROKER_URL: nats:4222
      MYSQL_URL: root:root@(db:3306)/root?charset=utf8&parseTime=True&loc=Local
      DB_CONNECTION_SLEEP: 15
    ports: 
      - 9191:9191
  prometheus:
    image: prom/prometheus
    networks:
      - local
      - monitoring
    volumes: 
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    networks: 
      - monitoring
    volumes: 
      - grafana-data
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports: 
      - 3000:3000
    depends_on:
      - prometheus
    